# Data for ideas 1-20. Score keys:
# pain wtp rec attr aware edu feas build ret comp expand boring excel market f10 f100
# comp: 10 = little competition (opportunity). edu/build: lower is better.

IDEAS_A = [
dict(id=1, name="SubShield — subcontractor COI tracking", ind="Construction",
 concept="Collect, read (AI), check and auto-chase subcontractor certificates of insurance against the GC's requirements; alert before expiry; audit-ready export.",
 customer="Commercial GCs & large specialty contractors, $5–50M revenue, 30–250 subs/yr",
 buyer="Office manager / project accountant / controller",
 problem="Every sub needs valid GL/auto/WC/umbrella coverage + endorsements; policies expire on staggered dates all year.",
 manual="Excel sheet + Outlook folder + calendar reminders; staff read ACORD 25 PDFs by hand and email agents.",
 sucks="Reading PDFs, chasing agents, and discovering lapses only at the insurer's premium audit.",
 freq="Weekly (some cert expires every week)", consequence="Premium-audit chargebacks for uninsured subs ($5k–$50k+), uninsured claims hitting the GC's policy.",
 swcat="COI / vendor insurance compliance tracking",
 competitors="BCS, myCOI, TrustLayer, Jones, Billy, PINS Advantage, SmartCompliance, Constrafor, Procore fields",
 comp_pricing="BCS: free ≤25 vendors, ~$0.95/vendor/mo self-serve (verified via search Oct 2026); entry tools ~$800–2,000/yr; enterprise $10k+/yr minimums",
 gaps="Low end is now cheap but mostly 'storage + reminders'; true automation (inbox ingestion, AI reading, agent chasing, premium-audit report) sits in sales-led tiers.",
 cat="A", domain="Low", mvp="3–4 weeks", price="$99–$399", channel="Outbound (calls + email) to GCs + construction insurance broker referrals",
 niche="Commercial GCs $5–50M in one Sun Belt metro", why_not="Crowded and price-compressed at the low end (BCS free tier); you must win on automation and distribution, not on features.",
 first_test="YES", first_where="Google Maps 'commercial general contractor <city>', state contractor license lookups (e.g., TX/FL/NC/AZ boards), AGC/ABC chapter member directories, LinkedIn titles 'project accountant'.",
 payment="Short demo required (self-serve possible at $99)",
 m1="Initial cleanup: dozens of expired/deficient certs found and chased.", m6="Renewals keep arriving weekly; the archive becomes audit evidence.", y2="Premium audits look back a year+; history + agent relationships make leaving painful.",
 value="Prevents fines/chargebacks, reduces liability, helps pass audits, saves admin time", must="Critical", tests="1,2,3,4,5,6,9,10,12 (9/12)",
 s=dict(pain=8,wtp=7,rec=9,attr=8,aware=9,edu=2,feas=8,build=4,ret=9,comp=3,expand=8,boring=9,excel=9,market=8,f10=8,f100=7)),

dict(id=2, name="Lien waiver collection for GCs", ind="Construction",
 concept="Each pay cycle, request conditional/unconditional lien waivers from subs & suppliers, e-sign, match to payments, block payment until received.",
 customer="Commercial/residential GCs with 20+ subs per month", buyer="Project accountant / AP",
 problem="Monthly pay apps require matching waivers from every sub and often lower tiers.",
 manual="Email PDFs, DocuSign one-offs, spreadsheet checklist per job.",
 sucks="Chasing signatures, wrong forms per state, payments delayed or released without waivers.",
 freq="Monthly per job", consequence="Double-payment/lien exposure, owner/lender withholding draws.",
 swcat="Lien waiver management", competitors="Procore Pay/Levelset, Built, Rabbet, Beam, Waivr, LienDone, GCPay, Textura",
 comp_pricing="Waivr and LienDone ~$49/mo (verified via search Oct 2026); enterprise via quote",
 gaps="Low end already served cheaply; high end bundled with payments.",
 cat="B", domain="Medium", mvp="3–4 weeks", price="$49–$199", channel="Same GC outbound as #1",
 niche="GCs on QuickBooks without Procore", why_not="$49 competitors + payment platforms bundling it free; best as a module of #1.",
 first_test="YES", first_where="Same sources as #1.", payment="Self-service",
 m1="Set up pay-cycle templates.", m6="Monthly pay cycles continue.", y2="Stays while projects run; but cheap substitutes exist.",
 value="Reduces liability, prevents lost money", must="Important", tests="1,2,3,4,5,9,10 (7/12)",
 s=dict(pain=7,wtp=5,rec=10,attr=8,aware=7,edu=3,feas=7,build=4,ret=8,comp=2,expand=7,boring=10,excel=8,market=7,f10=7,f100=6)),

dict(id=3, name="PayrollProof — certified payroll (WH-347) for public-works subcontractors", ind="Construction / Government contracts",
 concept="Import weekly payroll from QuickBooks/Gusto/ADP exports, map workers to projects & prevailing-wage classifications, check rates, generate WH-347 + Statement of Compliance + state forms/upload files.",
 customer="Subcontractors (electrical, concrete, paving, HVAC) with 10–150 workers doing prevailing-wage public works", buyer="Owner / payroll admin / office manager",
 problem="Every week on every public job, a certified payroll must be submitted with correct classifications, rates and fringes.",
 manual="Retyping payroll into WH-347 PDFs or Excel templates, then re-entering into agency portals (e.g., LCPtracker, state systems).",
 sucks="Hours of double entry weekly; rate errors trigger rejections, withheld payments, restitution.",
 freq="Weekly", consequence="Withheld progress payments, back-wage restitution, penalties, debarment risk.",
 swcat="Certified payroll software", competitors="LCPtracker (LCPcertified / LCPtracker Pro — imports QuickBooks & other payroll exports), Certified Payroll WH-347 (standalone), eBacon, Points North, Foundation/Sage/Viewpoint payroll modules",
 comp_pricing="Standalone WH-347 tool from ~$79/mo; LCPtracker Pro/eBacon ~$200–600/mo quote-based (via search Oct 2026)",
 gaps="LCPtracker already covers 'upload payroll export → federal/state CPRs', and many agencies pay for LCPtracker themselves. Remaining gaps: Gusto users (Gusto has no native certified payroll), small subs on many different agency portals, and pre-submission rate/fringe error checking.",
 cat="A", domain="Medium", mvp="4–6 weeks", price="$99–$349", channel="Outbound to contractors on public bid lists + construction bookkeepers/CPAs",
 niche="One state with its own prevailing-wage system (e.g., CA DIR registered contractors or a Midwest state) + federal Davis-Bacon",
 why_not="LCPtracker dominates both the agency and contractor sides; rules complexity (fringes, apprentices, state forms, WH-347 revisions) creates liability — a wrong rate on your watch is a customer's restitution bill.",
 first_test="YES", first_where="California DIR public-works contractor registration search (public), state DOT bid tabulations & awarded-contract lists, USAspending.gov subaward data, AGC chapter lists.",
 payment="Short demo required",
 m1="First weekly payrolls generated; immediate hours saved.", m6="Still weekly for every active public job.", y2="Public-works contractors bid public work year after year; history needed for audits.",
 value="Saves admin time, prevents fines/withheld payments, helps pass audits", must="Critical", tests="1,2,3,4,7,8,9,10,12 (9/12)",
 s=dict(pain=9,wtp=7,rec=10,attr=7,aware=9,edu=2,feas=6,build=5,ret=8,comp=3,expand=7,boring=10,excel=9,market=7,f10=7,f100=7)),

dict(id=4, name="Trade workforce license & certification tracker", ind="Construction / Home services",
 concept="Techs text in license/OSHA/EPA card photos; renewals & CE tracked; QR credential card; prequal packets.",
 customer="Electrical/plumbing/HVAC contractors with 15–150 field staff", buyer="HR/office manager",
 problem="Licenses & certs renew on staggered cycles with CE requirements.", manual="Spreadsheet + photocopies.",
 sucks="Lost cards, missed CE, scrambling for prequal packets.", freq="Monthly renewals; weekly requests for proof",
 consequence="Techs pulled from jobs, permit problems, fines.", swcat="Certification/expiration tracking",
 competitors="Expiration Reminder, SafetyCulture, Procore certifications, Connecteam, BambooHR/Rippling fields",
 comp_pricing="~$2–8/employee/mo or bundled (approx., unverified)", gaps="Generic; not trade-rule aware.",
 cat="B", domain="Low", mvp="2–3 weeks", price="$59–$249", channel="Trade associations + #1 cross-sell", niche="Electrical contractors in one licensing-heavy state",
 why_not="Moderate pain; HR tools absorb it; better as a module of #1.",
 first_test="YES", first_where="State electrical contractor license lists, Google Maps, IEC/PHCC chapters.", payment="Self-service",
 m1="Card collection.", m6="Renewals + turnover.", y2="CE history; only if bundled.",
 value="Prevents fines, saves time", must="Important", tests="1,2,3,4,5,6,10 (7/12)",
 s=dict(pain=6,wtp=5,rec=8,attr=8,aware=8,edu=3,feas=8,build=3,ret=7,comp=4,expand=6,boring=9,excel=9,market=6,f10=7,f100=6)),

dict(id=5, name="Subcontractor prequalification", ind="Construction",
 concept="Collect sub financials, EMR, safety programs, references; score and approve subs.",
 customer="GCs $20M+", buyer="Risk manager / preconstruction",
 problem="Annual prequal of every sub.", manual="Emailed questionnaires + Excel scoring.",
 sucks="Chasing forms, inconsistent scoring.", freq="Annual per sub (rolling)", consequence="Sub default risk.",
 swcat="Prequalification platforms", competitors="Autodesk TradeTapp, Highwire, ISNetworld, Avetta, Billy, Constrafor",
 comp_pricing="Mostly quote-based enterprise (unverified)", gaps="Small GCs priced out, but they also prequal less.",
 cat="C", domain="Medium", mvp="4 weeks", price="$149–$399", channel="GC outbound", niche="Mid-size GCs without TradeTapp",
 why_not="Annual cadence + buyer is larger GCs who already use enterprise tools.",
 first_test="YES", first_where="Same as #1.", payment="Sales call required",
 m1="Questionnaires sent.", m6="Quiet months.", y2="Annual refresh only.",
 value="Reduces liability", must="Important", tests="1,4,5,10 (4/12)",
 s=dict(pain=6,wtp=6,rec=6,attr=7,aware=6,edu=4,feas=7,build=4,ret=7,comp=3,expand=6,boring=8,excel=8,market=6,f10=6,f100=5)),

dict(id=6, name="OSHA 300 log & 300A electronic submission", ind="Construction / Manufacturing / Warehouses",
 concept="Record injuries, auto-build OSHA 300/301/300A, remind and prepare annual ITA submission.",
 customer="Employers with 20–250 staff in high-hazard industries", buyer="Safety/HR manager",
 problem="Injury recordkeeping + annual posting & electronic submission.", manual="Paper OSHA forms, Excel.",
 sucks="Annual scramble; recordability confusion.", freq="Per incident + annual", consequence="OSHA citations.",
 swcat="EHS incident management", competitors="OSHA's free ITA site, VelocityEHS, Intelex, SafetyCulture, many EHS suites",
 comp_pricing="Free government tooling to enterprise EHS (approx.)", gaps="Little; free forms suffice for small employers.",
 cat="B", domain="Low", mvp="1–2 weeks", price="$29–$79", channel="SEO", niche="Small manufacturers",
 why_not="Annual task + free government tools = subscribe-and-cancel.",
 first_test="YES", first_where="Google Maps, state manufacturer directories.", payment="Self-service",
 m1="Log entered.", m6="Nothing to do.", y2="Cancels between filing seasons.",
 value="Prevents fines", must="Important", tests="1,3,4,10 (4/12)",
 s=dict(pain=5,wtp=4,rec=4,attr=8,aware=8,edu=2,feas=8,build=2,ret=4,comp=3,expand=4,boring=9,excel=8,market=7,f10=6,f100=6)),

dict(id=7, name="DOT driver qualification (DQ) files", ind="Trucking",
 concept="Digital DQ files per 49 CFR 391; drivers text in med cards/CDLs; expiry alerts; audit export.",
 customer="Carriers with 3–50 trucks, especially new entrants", buyer="Owner / safety manager",
 problem="Required DQ documents expire constantly; new-entrant safety audit within 12 months.",
 manual="Paper binders, phone photos, spreadsheet.", sucks="Paper chaos, missed med cards.",
 freq="Monthly expirations; continuous hiring", consequence="Audit violations, conditional rating, insurance impact.",
 swcat="DQ file management", competitors="Roadworthy HQ, Core Compliance, DOTDriverFiles, J.J. Keller, Foley, Tenstreet, Motive/Samsara",
 comp_pricing="Core Compliance $15–$349/mo; Roadworthy HQ $39–$149/mo; DOTDriverFiles from ~$5/user (via search Oct 2026)",
 gaps="Cheap self-serve tools already exist; gap is mainly bilingual SMS-first UX and done-for-you setup.",
 cat="A", domain="Medium", mvp="3 weeks", price="$49–$199", channel="FMCSA census list → calls/email; insurance agents; factoring cos",
 niche="New-entrant carriers (0–18 months) with 2–15 trucks", why_not="Price war already underway ($15–$49 tools) + tiny carriers churn hard.",
 first_test="YES", first_where="FMCSA Company Census file / SAFER (public; includes many carrier emails & phones), FMCSA Register of new authority applicants.",
 payment="Self-service",
 m1="File cleanup.", m6="Med cards & reviews renew.", y2="Retention rule (employment + 3 yrs) — if the carrier survives.",
 value="Prevents fines, helps pass audits", must="Critical", tests="1,2,3,4,5,6,9,10,12 (9/12)",
 s=dict(pain=8,wtp=6,rec=9,attr=10,aware=9,edu=2,feas=7,build=4,ret=7,comp=2,expand=7,boring=9,excel=8,market=8,f10=9,f100=8)),

dict(id=8, name="IFTA quarterly fuel tax reporting", ind="Trucking",
 concept="Import miles by state + fuel receipts, compute IFTA return quarterly.",
 customer="Small interstate carriers without ELD IFTA reports", buyer="Owner",
 problem="Quarterly mileage/fuel tax returns.", manual="Trip sheets + receipts in shoeboxes + spreadsheets.",
 sucks="Tedious; audit risk.", freq="Quarterly", consequence="Penalties, audits, license suspension.",
 swcat="IFTA software", competitors="Motive/Samsara/other ELD built-ins, ExpressIFTA, TruckingOffice, IFTA filing services",
 comp_pricing="Often included free with ELD; standalone ~$10–$50/quarter (approx.)", gaps="Essentially none.",
 cat="A", domain="Medium", mvp="3 weeks", price="$15–$49", channel="FMCSA lists", niche="Non-ELD exempt carriers",
 why_not="ELDs give it away; quarterly use invites churn.",
 first_test="YES", first_where="FMCSA census.", payment="Self-service",
 m1="One return.", m6="Two returns.", y2="Switches to ELD bundle.",
 value="Saves time, prevents fines", must="Critical", tests="1,2,3,4,7,8 (6/12)",
 s=dict(pain=7,wtp=5,rec=9,attr=10,aware=10,edu=1,feas=7,build=4,ret=6,comp=1,expand=5,boring=9,excel=6,market=8,f10=8,f100=7)),

dict(id=9, name="Fleet maintenance & annual DOT inspection tracker", ind="Trucking / Field services",
 concept="PM schedules, annual inspection records, DVIR defects.", customer="Fleets 5–100 vehicles", buyer="Fleet manager",
 problem="Recurring PM + annual inspection proof.", manual="Spreadsheets + paper.", sucks="Missed services.",
 freq="Weekly/monthly", consequence="Breakdowns, roadside violations.", swcat="Fleet maintenance software",
 competitors="Fleetio, Whip Around, Samsara, Motive, AUTOsist, Fleet Maintenance Pro",
 comp_pricing="~$4–$10/vehicle/mo (approx.)", gaps="Very few.", cat="A", domain="Low", mvp="4 weeks", price="$49–$199",
 channel="FMCSA lists", niche="Small fleets", why_not="Mature, well-funded competitors with integrations.",
 first_test="YES", first_where="FMCSA census.", payment="Self-service",
 m1="Asset setup.", m6="Ongoing PMs.", y2="Sticky — but for incumbents.",
 value="Prevents downtime/fines", must="Important", tests="1,2,3,4,9,10 (6/12)",
 s=dict(pain=6,wtp=5,rec=9,attr=9,aware=9,edu=2,feas=7,build=4,ret=7,comp=1,expand=6,boring=7,excel=7,market=8,f10=7,f100=6)),

dict(id=10, name="Freight broker carrier vetting & monitoring", ind="Logistics",
 concept="Monitor carrier authority, insurance, safety and fraud signals before tendering loads.",
 customer="Freight brokerages", buyer="Carrier relations / compliance",
 problem="Double brokering & fraud; insurance lapses.", manual="SAFER lookups, calls.", sucks="Fraud losses.",
 freq="Daily", consequence="Stolen loads, liability.", swcat="Carrier onboarding/monitoring",
 competitors="Highway, Carrier Assure, RMIS (Truckstop), MyCarrierPackets, Carrier411, DAT",
 comp_pricing="Hundreds to thousands per month (approx.)", gaps="Fraud-signal data is the moat; incumbents have it.",
 cat="A", domain="High", mvp="2–3 months", price="$200–$1,000", channel="Broker outbound", niche="Small brokerages",
 why_not="Data-network moat + fierce incumbents; fraud detection needs proprietary data.",
 first_test="YES", first_where="FMCSA broker authority list.", payment="Sales call required",
 m1="Onboarding.", m6="Daily use.", y2="Sticky for winners.",
 value="Prevents losses, reduces liability", must="Critical", tests="1,2,3,5,9,10,12 (7/12)",
 s=dict(pain=8,wtp=8,rec=10,attr=8,aware=10,edu=1,feas=4,build=7,ret=8,comp=1,expand=7,boring=6,excel=3,market=7,f10=5,f100=4)),

dict(id=11, name="Provider credentialing & CAQH re-attestation tracker", ind="Healthcare administration",
 concept="Track licenses, DEA, board certs, malpractice, CAQH 120-day attestation, payer revalidation; provider self-service; monthly exclusion checks.",
 customer="Group practices (behavioral health, PT, primary care) with 5–40 clinicians; freelance credentialers",
 buyer="Practice manager / credentialing specialist",
 problem="Dozens of overlapping renewal cycles; lapses stop billing.", manual="Spreadsheets, portal logins, calendar.",
 sucks="Denials discovered weeks later; knowledge lost with staff turnover.", freq="Weekly (across providers)",
 consequence="Denied/delayed claims ($10k+ per lapse), compliance findings.", swcat="Credentialing software / CVO",
 competitors="Medallion, Verifiable, CredentialStream, symplr, Modio, Andros, outsourced credentialing firms",
 comp_pricing="Outsourced ~$100–$300/provider/mo; software mostly quote-based (approx., unverified)",
 gaps="Venture players moving upmarket; small groups underserved by self-serve software.",
 cat="A", domain="Medium", mvp="4–5 weeks", price="$99–$499", channel="Practice-owner communities, billing companies, freelance credentialers",
 niche="Behavioral-health group practices 5–30 clinicians", why_not="Sensitive PII (SSN/DOB/DEA) raises security bar; buyers overloaded; money pulls toward services.",
 first_test="YES", first_where="CMS NPPES NPI registry (public, filter by taxonomy + organization), state licensing boards, Psychology Today group listings.",
 payment="Short demo required",
 m1="Data loaded; gaps found.", m6="CAQH cycles + renewals.", y2="Source of truth for every provider; switching is painful.",
 value="Prevents lost revenue, helps pass audits, saves time", must="Critical", tests="1,2,3,4,5,6,9,10,12 (9/12)",
 s=dict(pain=9,wtp=8,rec=9,attr=7,aware=9,edu=3,feas=6,build=5,ret=9,comp=4,expand=8,boring=9,excel=8,market=8,f10=6,f100=6)),

dict(id=12, name="Monthly OIG/SAM/state Medicaid exclusion screening", ind="Healthcare administration",
 concept="Screen every employee/contractor monthly against federal and state exclusion lists; store evidence.",
 customer="Home health, pharmacies, DME, clinics, behavioral health employers 10–500 staff", buyer="Compliance/HR",
 problem="Monthly screening expected by Medicaid programs; hiring excluded persons risks repayment.",
 manual="Manual searches on OIG/SAM sites, screenshots to folders.", sucks="Tedious, easily skipped.",
 freq="Monthly", consequence="Civil monetary penalties, overpayment recovery.", swcat="Exclusion screening",
 competitors="ProviderTrust, Verisys, Streamline Verify, Exclusion Screening LLC, background-check vendors",
 comp_pricing="~$1–$5/person/mo or flat (approx., unverified)", gaps="Commodity; cheap options exist.",
 cat="A", domain="Medium", mvp="2–3 weeks (federal), +weeks per state list", price="$49–$199", channel="SEO + healthcare compliance consultants",
 niche="Home health agencies in one state", why_not="Commodity data product; state-list maintenance is grindy; better as a feature of #11/#13.",
 first_test="YES", first_where="CMS Care Compare provider data, state licensing lists.", payment="Self-service",
 m1="First screen.", m6="Monthly screens + evidence.", y2="Audit trail retained.",
 value="Prevents fines, helps pass audits", must="Critical", tests="1,2,3,9,10,12 (6/12)",
 s=dict(pain=7,wtp=5,rec=10,attr=8,aware=9,edu=2,feas=8,build=3,ret=8,comp=3,expand=5,boring=10,excel=6,market=7,f10=7,f100=6)),

dict(id=13, name="Home care caregiver compliance files", ind="Healthcare administration",
 concept="Track caregiver TB tests, CPR, background checks, training hours, I-9, competencies against state rules.",
 customer="Private-duty/home care agencies 20–300 caregivers", buyer="Agency owner / HR coordinator",
 problem="State surveys check staff files; caregiver turnover is extreme.", manual="Spreadsheets + paper files.",
 sucks="Constant churn = constant gaps.", freq="Weekly", consequence="Survey citations, payer audits.",
 swcat="Home care agency software (compliance module)", competitors="HHAeXchange, CareTime, ShiftCare, AxisCare, WellSky, AlayaCare, eCaring",
 comp_pricing="Bundled into agency platforms (via search Oct 2026)", gaps="Mostly covered inside the systems agencies already use.",
 cat="B", domain="Medium", mvp="3 weeks", price="$99–$299", channel="State home care associations", niche="Agencies on weak scheduling software",
 why_not="Agency platforms already include expiring-document tracking; you'd be a redundant add-on.",
 first_test="YES", first_where="State home care license lists, Google Maps.", payment="Short demo required",
 m1="Files cleaned.", m6="Turnover keeps it busy.", y2="Unless platform replaces it.",
 value="Helps pass audits", must="Important", tests="1,2,3,4,5,6,10 (7/12)",
 s=dict(pain=8,wtp=6,rec=9,attr=9,aware=7,edu=3,feas=7,build=4,ret=8,comp=3,expand=6,boring=9,excel=8,market=7,f10=7,f100=7)),

dict(id=14, name="Dental insurance eligibility & benefits verification", ind="Healthcare administration",
 concept="Verify patients' coverage before appointments; write breakdowns into the PMS.",
 customer="Dental practices 1–10 locations", buyer="Office manager",
 problem="Front desk spends hours on portals/phones.", manual="Portals, phone calls, offshore teams.", sucks="Slow, error-prone.",
 freq="Daily", consequence="Surprise balances, write-offs.", swcat="Dental RCM/eligibility",
 competitors="Vyne Trellis, Zuub, Onederful, DentalXChange, AI voice-agent startups, offshore VAs",
 comp_pricing="~$300–$1,000+/location/mo (approx.)", gaps="Data completeness; still needs humans.",
 cat="A", domain="High", mvp="3+ months", price="$299–$799", channel="Dental consultants", niche="Open Dental practices",
 why_not="PMS integrations + PHI + payer variance = not a solo 2–6 week build.",
 first_test="YES", first_where="Google Maps, state dental boards.", payment="Sales call required",
 m1="Daily use.", m6="Daily use.", y2="Sticky if accurate.",
 value="Saves staff cost, prevents lost revenue", must="Important", tests="1,2,4,8,12 (5/12)",
 s=dict(pain=9,wtp=8,rec=10,attr=8,aware=9,edu=2,feas=3,build=9,ret=8,comp=4,expand=8,boring=7,excel=6,market=8,f10=5,f100=5)),

dict(id=15, name="City rental license & registration compliance", ind="Property management",
 concept="Track per-property rental licenses, registrations, inspections, lead/smoke certificates by city.",
 customer="Landlords/PMs with 20–500 doors across several cities", buyer="Owner / PM",
 problem="City rental programs renew annually with inspections.", manual="Calendar + folders.", sucks="Every city differs.",
 freq="Annual per property (monthly across portfolio)", consequence="Fines, inability to evict/collect in some cities.",
 swcat="None clear", competitors="PM software notes, consultants", comp_pricing="n/a", gaps="Open, but data curation heavy.",
 cat="C", domain="Medium", mvp="4 weeks + data", price="$49–$199", channel="Local landlord associations", niche="One metro with strict programs",
 why_not="Customers tolerate it; per-city rule curation is endless.",
 first_test="MAYBE", first_where="City rental registries (some public), landlord associations.", payment="Short demo required",
 m1="Setup.", m6="Few events.", y2="Low engagement.",
 value="Prevents fines", must="Important", tests="1,2,3,4,6 (5/12)",
 s=dict(pain=6,wtp=5,rec=7,attr=6,aware=5,edu=5,feas=5,build=5,ret=6,comp=7,expand=5,boring=9,excel=8,market=5,f10=5,f100=4)),

dict(id=16, name="Renter's insurance verification for PMs", ind="Property management",
 concept="Verify tenants keep required renter's insurance.", customer="PMs 200+ units", buyer="PM ops",
 problem="Leases require coverage; tenants lapse.", manual="Email/PDF checks.", sucks="Endless follow-up.",
 freq="Monthly", consequence="Uninsured damage.", swcat="Insurance compliance for PMs",
 competitors="Second Nature, Sure, Assurant, AppFolio/Buildium programs, master-policy providers",
 comp_pricing="Often free to PMs (they earn revenue from master policies)", gaps="None — incumbents pay PMs.",
 cat="B", domain="Medium", mvp="3 weeks", price="$99–$299", channel="—", niche="—",
 why_not="Competitors give it away and pay PMs a revenue share.",
 first_test="YES", first_where="Google Maps, NARPM.", payment="Sales call required",
 m1="—", m6="—", y2="—", value="Reduces liability", must="Important", tests="1,3,5,6,9 (5/12)",
 s=dict(pain=6,wtp=5,rec=9,attr=7,aware=7,edu=3,feas=6,build=5,ret=6,comp=1,expand=5,boring=8,excel=6,market=6,f10=5,f100=4)),

dict(id=17, name="Affordable housing tenant income recertifications", ind="Property management",
 concept="Annual LIHTC/HUD recertification workflows.", customer="Affordable housing PMs", buyer="Compliance director",
 problem="Annual recerts with strict rules.", manual="Paper files + specialized software.", sucks="Complex, audited.",
 freq="Monthly across portfolio", consequence="Loss of tax credits, findings.", swcat="Affordable housing compliance",
 competitors="Yardi, RealPage, Entrata, Boston Post, specialized consultants", comp_pricing="Enterprise",
 gaps="Rules expertise is the barrier.", cat="A", domain="High", mvp="3+ months", price="$300+",
 channel="Industry events", niche="—", why_not="Requires deep regulatory expertise; errors are catastrophic.",
 first_test="MAYBE", first_where="State housing finance agency property lists.", payment="Enterprise sales required",
 m1="—", m6="—", y2="—", value="Prevents loss of credits", must="Critical", tests="1,2,3,4,5,10,12 (7/12)",
 s=dict(pain=9,wtp=8,rec=10,attr=6,aware=9,edu=3,feas=2,build=9,ret=9,comp=3,expand=7,boring=10,excel=6,market=7,f10=4,f100=4)),

dict(id=18, name="Bookkeeper client 'missing items' chaser", ind="Accounting",
 concept="Text/email clients about uncategorized transactions & missing receipts; answers write back.",
 customer="Bookkeeping firms 15–150 clients", buyer="Firm owner",
 problem="Month-end blocked by unresponsive clients.", manual="Emailed spreadsheets.", sucks="Clients ignore emails.",
 freq="Monthly", consequence="Late closes, unhappy clients.", swcat="Client request tools",
 competitors="Keeper, Financial Cents, Karbon, Content Snare, TaxDome, QuickBooks Ask Client",
 comp_pricing="~$20–$80/user/mo (approx.)", gaps="Keeper covers this specifically and well.",
 cat="B", domain="Low", mvp="3 weeks", price="$49–$199", channel="Bookkeeper communities", niche="—",
 why_not="Well-funded incumbent solves exactly this.",
 first_test="YES", first_where="QuickBooks ProAdvisor directory, Google Maps.", payment="Self-service",
 m1="—", m6="—", y2="—", value="Saves time", must="Important", tests="1,4,5,11 (4/12)",
 s=dict(pain=7,wtp=5,rec=10,attr=8,aware=7,edu=3,feas=7,build=4,ret=7,comp=1,expand=5,boring=8,excel=8,market=7,f10=7,f100=6)),

dict(id=19, name="Bank statement PDF → CSV conversion for accountants", ind="Accounting",
 concept="Convert statements to clean transactions for cleanup work.", customer="Accountants doing catch-up bookkeeping", buyer="Accountant",
 problem="Clients send PDF statements.", manual="Manual typing.", sucks="Hours of data entry.",
 freq="Project-based", consequence="Time lost.", swcat="Statement converters",
 competitors="DocuClipper, MoneyThumb, Dext, Hubdoc, many AI tools", comp_pricing="~$20–$100/mo (approx.)",
 gaps="None; AI made it a commodity.", cat="A", domain="Low", mvp="1–2 weeks", price="$29–$99",
 channel="SEO", niche="—", why_not="Commodity; project-based usage = churn.",
 first_test="YES", first_where="ProAdvisor directory.", payment="Self-service",
 m1="Used.", m6="Sporadic.", y2="Cancelled.", value="Saves time", must="Convenience", tests="1,4,8 (3/12) — FAILS test",
 s=dict(pain=6,wtp=5,rec=5,attr=8,aware=9,edu=2,feas=8,build=4,ret=4,comp=1,expand=4,boring=8,excel=7,market=6,f10=7,f100=6)),

dict(id=20, name="Vendor W-9 collection & 1099 prep", ind="Accounting",
 concept="Collect W-9s, TIN-match, prepare 1099s.", customer="SMBs & bookkeepers", buyer="AP / bookkeeper",
 problem="Missing W-9s at year-end.", manual="Email + PDFs.", sucks="January scramble.",
 freq="Annual peak", consequence="IRS penalties.", swcat="1099 software",
 competitors="Track1099, Tax1099, QuickBooks, Gusto, Bill.com", comp_pricing="Per-form pricing (approx.)",
 gaps="None.", cat="A", domain="Low", mvp="2 weeks", price="$19–$49", channel="—", niche="—",
 why_not="Seasonal; bundled everywhere — a feature of #1.",
 first_test="YES", first_where="Anywhere.", payment="Self-service", m1="—", m6="Idle.", y2="Cancelled.",
 value="Prevents fines", must="Important", tests="1,2,3,5 (4/12)",
 s=dict(pain=5,wtp=4,rec=3,attr=8,aware=9,edu=2,feas=9,build=2,ret=3,comp=2,expand=4,boring=9,excel=8,market=7,f10=7,f100=6)),
]
