IDEA_19 = dict(id=19, name="STR permit & occupancy-tax deadline tracker", ind="Property management (short-term rentals)",
 concept="Per-listing local permit numbers, renewals, inspections and occupancy-tax filing deadlines across jurisdictions.",
 customer="STR property managers with 10–300 listings across several cities", buyer="Owner / ops manager",
 problem="Local STR rules, permits and tax filings differ by city and change often.", manual="Spreadsheets + calendars + city portals.",
 sucks="Every jurisdiction differs; rules change; permit numbers must appear on listings.", freq="Monthly (filings) / annual (permits)",
 consequence="Fines, delisting, lost bookings.", swcat="STR compliance (operator side)",
 competitors="Avalara MyLodgeTax (tax filing), Granicus Host Compliance (sells to cities), consultants",
 comp_pricing="Tax filing services per listing/filing (approx., unverified)", gaps="Operator-side permit tracking poorly served.",
 cat="B", domain="Medium", mvp="4 weeks + data curation", price="$79–$299", channel="PMS marketplaces (Hostaway/Guesty), VRMA, STR groups",
 niche="Managers in 1–2 heavily regulated states", why_not="Endless jurisdiction-data maintenance; regulation can ban a market overnight.",
 first_test="MAYBE", first_where="Airbnb/VRBO host profiles, VRMA members, Google Maps 'vacation rental management'.", payment="Short demo required",
 m1="Permits mapped.", m6="Filings + renewals.", y2="Data moat — if markets survive.",
 value="Prevents fines, prevents lost revenue", must="Critical", tests="1,2,3,4,6 (5/12)",
 s=dict(pain=7,wtp=6,rec=8,attr=6,aware=7,edu=4,feas=5,build=5,ret=7,comp=6,expand=5,boring=9,excel=8,market=5,f10=5,f100=5))

IDEAS_B = [
dict(id=21, name="Attorney CLE tracking for firms", ind="Legal operations",
 concept="Track each attorney's CLE credits & deadlines across states.", customer="Law firms 10–100 attorneys", buyer="Office administrator",
 problem="Multi-state CLE deadlines.", manual="Spreadsheet + bar portals.", sucks="Last-minute scrambles.",
 freq="Annual/biennial", consequence="Late fees, suspension (rare).", swcat="CLE tracking",
 competitors="State bar portals, CLE providers' trackers, practice management add-ons", comp_pricing="Often free",
 gaps="Little.", cat="B", domain="Low", mvp="2 weeks", price="$49–$149", channel="Legal admin associations", niche="Multi-state firms",
 why_not="Bars and CLE vendors provide free tracking; low urgency.",
 first_test="YES", first_where="State bar directories, Martindale.", payment="Self-service",
 m1="Setup.", m6="Idle.", y2="Low value.", value="Prevents fines", must="Convenience", tests="1,3,4,6 (4/12)",
 s=dict(pain=4,wtp=4,rec=6,attr=8,aware=7,edu=3,feas=8,build=2,ret=5,comp=4,expand=4,boring=9,excel=7,market=5,f10=6,f100=5)),

dict(id=22, name="Court deadline docketing for small law firms", ind="Legal operations",
 concept="Rules-based deadline calculation from court events.", customer="Litigation firms 2–30 lawyers", buyer="Managing partner",
 problem="Missed deadlines = malpractice.", manual="Paralegal calendars.", sucks="High-stakes manual math.",
 freq="Daily", consequence="Malpractice claims.", swcat="Docketing/court rules",
 competitors="CompuLaw (Aderant), LawToolBox, CalendarRules, Clio integrations", comp_pricing="~$50–$200/user/mo (approx.)",
 gaps="Rules data is the moat.", cat="A", domain="High", mvp="6+ months", price="$200+", channel="—", niche="—",
 why_not="Rules database maintenance + malpractice liability; incumbent moat.",
 first_test="YES", first_where="State bar directories.", payment="Sales call required",
 m1="—", m6="—", y2="—", value="Reduces liability", must="Critical", tests="1,2,3,9,10 (5/12)",
 s=dict(pain=9,wtp=8,rec=10,attr=8,aware=9,edu=2,feas=3,build=8,ret=9,comp=3,expand=7,boring=9,excel=5,market=7,f10=5,f100=5)),

dict(id=23, name="Calibration & gauge management for ISO shops/labs", ind="Manufacturing",
 concept="Asset register, calibration due dates, AI cert intake, out-of-tolerance log, audit report.",
 customer="Machine shops/small manufacturers/labs with 50–2,000 gauges", buyer="Quality manager",
 problem="6–12-month calibration cycles; auditors demand traceability.", manual="Spreadsheets + emailed cal certs.",
 sucks="Old desktop tools; audit scrambles.", freq="Weekly due items", consequence="ISO audit findings; customer loss.",
 swcat="Calibration management", competitors="GAGEtrak, IndySoft, Qualer, CMMS vendors (MaintainX, UpKeep, Limble)",
 comp_pricing="Desktop licences/quotes (approx.)", gaps="Modern, cheap, cloud UX.", cat="B", domain="Medium", mvp="3 weeks",
 price="$79–$249", channel="ISO consultants & registrars", niche="ISO 9001 machine shops", why_not="Slower sales; modest market; CMMS tools creep in.",
 first_test="YES", first_where="IAF CertSearch / registrar certified-company lists, Thomasnet, Google Maps 'machine shop'.", payment="Short demo required",
 m1="Assets loaded.", m6="Cal cycles.", y2="Audit history.", value="Helps pass audits", must="Important", tests="1,3,4,6,9,10 (6/12)",
 s=dict(pain=6,wtp=6,rec=8,attr=6,aware=7,edu=3,feas=8,build=4,ret=8,comp=5,expand=6,boring=9,excel=9,market=5,f10=5,f100=5)),

dict(id=24, name="Supplier document management for small food manufacturers (FSMA)", ind="Manufacturing (food)",
 concept="Collect & track supplier COAs, GFSI certificates, allergen statements, insurance, letters of guarantee; expiry alerts; audit binder.",
 customer="Food manufacturers/co-packers with 30–300 ingredient suppliers", buyer="QA/food safety manager",
 problem="FSMA supplier verification + SQF/BRCGS audits require current supplier docs.", manual="Shared folders + spreadsheets + email.",
 sucks="Expired certs found during audits; endless chasing.", freq="Weekly", consequence="Audit non-conformances, lost retailer accounts, recalls.",
 swcat="Supplier compliance management", competitors="TraceGains, Trustwell (FoodLogiQ), SafetyChain, Redzone, generic QMS",
 comp_pricing="Mostly quote-based mid-market/enterprise (approx., unverified)", gaps="Small plants (<$50M) priced out; spreadsheets dominate.",
 cat="B", domain="Medium", mvp="4 weeks", price="$149–$399", channel="GFSI certified-site directories → outbound; food safety consultants",
 niche="SQF-certified small manufacturers", why_not="Buyer reach is fragmented; QA managers buy slowly; TraceGains network effect.",
 first_test="YES", first_where="SQFI certified-site search and BRCGS directory (public), state food processor licenses.", payment="Short demo required",
 m1="Supplier docs collected.", m6="Continuous expirations.", y2="Audit history + supplier network.", value="Helps pass audits, reduces liability", must="Critical", tests="1,2,3,4,5,6,10 (7/12)",
 s=dict(pain=7,wtp=7,rec=9,attr=6,aware=7,edu=4,feas=6,build=5,ret=8,comp=5,expand=7,boring=10,excel=9,market=6,f10=5,f100=5)),

dict(id=25, name="Forklift operator certs & daily pre-shift inspections", ind="Warehouses",
 concept="Operator 3-year evaluations + daily checklist by phone.", customer="Warehouses 10–200 staff", buyer="Ops/safety manager",
 problem="OSHA 1910.178 training & inspections.", manual="Paper checklists.", sucks="Pencil-whipped paper.",
 freq="Daily", consequence="OSHA citations, injuries.", swcat="Inspection checklists",
 competitors="SafetyCulture, telematics vendors, paper", comp_pricing="~$0–$25/user (approx.)", gaps="Little.",
 cat="C", domain="Low", mvp="2 weeks", price="$29–$99", channel="—", niche="—", why_not="Low WTP; generic checklist apps cover it.",
 first_test="YES", first_where="Google Maps 'warehouse'.", payment="Self-service", m1="—", m6="—", y2="—",
 value="Prevents fines", must="Important", tests="1,3,9,10 (4/12)",
 s=dict(pain=5,wtp=4,rec=9,attr=7,aware=6,edu=4,feas=8,build=3,ret=6,comp=4,expand=4,boring=8,excel=4,market=6,f10=5,f100=5)),

dict(id=26, name="Safety Data Sheet (SDS) library management", ind="Manufacturing / Facilities",
 concept="Maintain current SDS binder, QR access.", customer="Any chemical-using business", buyer="Safety manager",
 problem="HazCom requires accessible current SDSs.", manual="Paper binders.", sucks="Outdated sheets.",
 freq="Monthly updates", consequence="OSHA HazCom citations.", swcat="SDS management",
 competitors="VelocityEHS (MSDSonline), Chemical Safety, SDS Manager, KHA", comp_pricing="Free tiers to enterprise",
 gaps="None.", cat="A", domain="Low", mvp="3 weeks", price="$29–$99", channel="—", niche="—",
 why_not="Mature market with free tiers and large SDS databases.",
 first_test="YES", first_where="Google Maps.", payment="Self-service", m1="—", m6="—", y2="—",
 value="Prevents fines", must="Important", tests="1,3,6,10 (4/12)",
 s=dict(pain=5,wtp=5,rec=6,attr=8,aware=9,edu=2,feas=7,build=5,ret=7,comp=1,expand=5,boring=9,excel=6,market=7,f10=6,f100=5)),

dict(id=27, name="Insurance agency producer license & appointment tracking", ind="Insurance administration",
 concept="NIPR-synced license/CE/appointment tracking for agency producers.", customer="P&C/life agencies 5–50 producers", buyer="Agency principal / ops",
 problem="Multi-state licenses & CE renew constantly.", manual="Spreadsheet + NIPR alerts.", sucks="Missed CE, unlicensed sales.",
 freq="Monthly", consequence="Regulatory fines, commission chargebacks.", swcat="Producer licensing",
 competitors="TrustLayer (free ≤50 producers), AgentSync, InsureTrek, Agenzee, Sircon, NIPR alerts",
 comp_pricing="TrustLayer free for up to 50 producers (via search Oct 2026)", gaps="None at the small end.",
 cat="A", domain="Low", mvp="2 weeks", price="$49–$149", channel="—", niche="—", why_not="A free, well-funded competitor owns the small-agency tier.",
 first_test="YES", first_where="State DOI agency license lookups, Google Maps.", payment="Self-service", m1="—", m6="—", y2="—",
 value="Prevents fines", must="Important", tests="1,2,3,4,6 (5/12)",
 s=dict(pain=6,wtp=4,rec=8,attr=8,aware=9,edu=2,feas=8,build=3,ret=7,comp=1,expand=5,boring=10,excel=8,market=6,f10=6,f100=5)),

dict(id=28, name="CommissionCheck — carrier commission reconciliation for independent P&C agencies", ind="Insurance administration",
 concept="Upload/forward monthly carrier commission statements (PDF/Excel/CSV) + AMS export; AI normalizes and matches policies; flags missing, short-paid and chargeback items; tracks recovery.",
 customer="Independent P&C agencies with $1–15M premium-based revenue and 10–60 carrier/MGA relationships", buyer="Agency owner / office manager / agency accountant",
 problem="Dozens of carrier statements in different formats every month must be reconciled to expected commissions.",
 manual="Download statements from carrier portals, retype or paste into Excel, tick-and-tie against AMS reports.",
 sucks="Days per month of tedious matching; missed commissions are rarely recovered.", freq="Monthly",
 consequence="Lost revenue (missed/short-paid commissions), producer pay errors, messy books.", swcat="Commission reconciliation",
 competitors="Applied Recon (inside Applied Epic), AMS direct-bill/commission features (HawkSoft, AMS360, EZLynx, NowCerts), IVANS commission download, Commission Wizard, outsourced accounting",
 comp_pricing="Commission Wizard from ~$199/mo (via search Oct 2026); Applied Recon bundled/priced for Epic users",
 gaps="Small agencies on non-Epic AMSs with many MGA/wholesaler statements that don't come via IVANS download.",
 cat="B", domain="Medium", mvp="4–6 weeks", price="$149–$499", channel="Outbound to independent agencies + agency accounting consultants + Big I / agency networks",
 niche="Agencies with 15–60 carriers/MGAs on HawkSoft/EZLynx/NowCerts", why_not="Statement format chaos makes accuracy hard; Applied/AMS vendors are moving in; a newer AI competitor already targets this exact niche.",
 first_test="YES", first_where="State DOI agency license databases, Google Maps 'independent insurance agency', Trusted Choice/Big I directories, agency network member lists.",
 payment="Short demo required",
 m1="Backlog reconciled; first missing commissions found.", m6="Monthly statements never stop.", y2="Mapping rules per carrier accumulate — switching cost.",
 value="Prevents lost revenue, saves admin time", must="Important", tests="1,2,4,5,7,8,9,12 (8/12)",
 s=dict(pain=8,wtp=7,rec=10,attr=9,aware=7,edu=3,feas=6,build=6,ret=8,comp=4,expand=7,boring=10,excel=10,market=7,f10=7,f100=7)),

dict(id=29, name="Childcare center staff compliance files", ind="Education administration",
 concept="Track staff background checks, CPR, TB, training hours vs state licensing; inspector-ready export.",
 customer="Childcare centers 1–10 sites", buyer="Center director / owner",
 problem="Licensing inspectors review staff files; high turnover.", manual="Paper binders.", sucks="Gaps found at inspection.",
 freq="Monthly", consequence="Citations.", swcat="Childcare management (staff module)",
 competitors="Brightwheel, Procare, Kangarootime, Playground, state training registries", comp_pricing="Bundled",
 gaps="Staff compliance secondary in parent-facing platforms.", cat="C", domain="Medium", mvp="3 weeks", price="$49–$149",
 channel="State childcare associations", niche="Independent centers in one state", why_not="Thin-margin buyers; platforms likely to bundle.",
 first_test="YES", first_where="State childcare licensing search databases (public).", payment="Self-service",
 m1="Files fixed.", m6="Turnover.", y2="Annual hours.", value="Helps pass inspections", must="Important", tests="1,3,4,6,10 (5/12)",
 s=dict(pain=7,wtp=5,rec=8,attr=9,aware=6,edu=3,feas=7,build=3,ret=7,comp=4,expand=5,boring=9,excel=8,market=6,f10=7,f100=6)),

dict(id=30, name="Nonprofit grant reporting deadline tracker", ind="Nonprofits",
 concept="Track grant deliverables, reports, and budgets.", customer="Nonprofits with 10+ grants", buyer="Development director",
 problem="Missed grant reports.", manual="Spreadsheets.", sucks="Scattered deadlines.", freq="Monthly", consequence="Lost future funding.",
 swcat="Grant management", competitors="Instrumentl, Submittable, Fluxx, Foundant", comp_pricing="~$100–$300/mo (approx.)",
 gaps="Few.", cat="C", domain="Low", mvp="2 weeks", price="$29–$99", channel="—", niche="—", why_not="Weak wallets; long approvals.",
 first_test="YES", first_where="IRS EO data, Candid/GuideStar.", payment="Short demo required", m1="—", m6="—", y2="—",
 value="Prevents lost funding", must="Important", tests="1,2,4,7 (4/12)",
 s=dict(pain=5,wtp=3,rec=7,attr=6,aware=6,edu=3,feas=8,build=3,ret=6,comp=5,expand=4,boring=8,excel=9,market=5,f10=5,f100=4)),

dict(id=31, name="Backflow tester route & retest manager", ind="Home services / Field services",
 concept="Tester's customer device list, annual retest reminders to customers, mobile test entry, PDF report, utility submission tracking.",
 customer="Certified backflow testers & small plumbing companies with 200–3,000 devices", buyer="Owner-tester",
 problem="Every device needs an annual test and a report filed with the utility within days.", manual="Paper forms, spreadsheets, utility portals.",
 sucks="Retests missed = lost revenue; duplicate data entry into utility portals.", freq="Daily in season; annual per device",
 consequence="Lost repeat revenue; late report penalties from utilities.", swcat="Backflow software (tester side)",
 competitors="FAST Tester, Syncta, utility portals (Tokay, SwiftComply, BSI Online)", comp_pricing="Utility portals free to testers; tester apps vary (via search Oct 2026)",
 gaps="Tester-side revenue tools (retest reminders) are thin.", cat="B", domain="Low", mvp="3 weeks", price="$49–$99",
 channel="State certified tester lists", niche="Testers in one state", why_not="Small market; low ARPU; utility portals cover reporting.",
 first_test="YES", first_where="State/utility certified backflow tester lists (often public PDFs).", payment="Self-service",
 m1="Device list loaded.", m6="Retests flowing.", y2="Revenue engine.", value="Makes money (retest revenue), prevents penalties", must="Important", tests="1,2,3,4,9,10 (6/12)",
 s=dict(pain=6,wtp=5,rec=9,attr=7,aware=7,edu=3,feas=8,build=4,ret=8,comp=5,expand=4,boring=10,excel=7,market=3,f10=6,f100=5)),

dict(id=32, name="Franchisee compliance document collection", ind="Franchises",
 concept="Franchisor collects each location's COIs, licenses, health inspections, and required reports with reminders.",
 customer="Franchisors with 20–300 units", buyer="Franchise ops / compliance",
 problem="Franchise agreements require ongoing proof from franchisees.", manual="Email + shared drives.", sucks="Chasing hundreds of owners.",
 freq="Monthly", consequence="Brand liability, uninsured incidents.", swcat="Franchise compliance / COI",
 competitors="TrustLayer, BCS, FranConnect, Naranga, FranIQ, AI agent builders", comp_pricing="Varies; BCS/TrustLayer serve franchise COIs",
 gaps="Mixed documents beyond COIs.", cat="C", domain="Low", mvp="3 weeks", price="$199–$599", channel="Franchise directories + FDD filings",
 niche="Emerging franchisors 20–100 units", why_not="Sales-led; COI vendors already market to franchisors; it's #1 with a different buyer.",
 first_test="YES", first_where="State FDD databases (CA DFPI, WI, MN — public), Entrepreneur Franchise 500, IFA members.", payment="Sales call required",
 m1="Docs collected.", m6="Renewals.", y2="Sticky.", value="Reduces liability", must="Important", tests="1,3,5,6,10,11 (6/12)",
 s=dict(pain=7,wtp=6,rec=9,attr=7,aware=6,edu=4,feas=7,build=4,ret=8,comp=3,expand=7,boring=9,excel=8,market=5,f10=5,f100=4)),

dict(id=33, name="Restaurant food-safety temp logs", ind="Restaurants",
 concept="Digital temp logs + checklists.", customer="Restaurants 1–20 units", buyer="Owner/GM",
 problem="Daily logs for inspections.", manual="Paper clipboards.", sucks="Pencil-whipping.",
 freq="Daily", consequence="Health violations.", swcat="Food safety",
 competitors="Jolt, ComplianceMate, Crunchtime, FoodDocs, SafetyCulture", comp_pricing="~$50–$150/location (approx.)",
 gaps="Hardware sensors needed for real value.", cat="B", domain="Low", mvp="3 weeks (sensors months)", price="$49–$149",
 channel="—", niche="—", why_not="Hardware, thin margins, high churn.",
 first_test="YES", first_where="Google Maps, health inspection data.", payment="Self-service", m1="—", m6="—", y2="—",
 value="Prevents fines", must="Important", tests="1,3,9,10 (4/12)",
 s=dict(pain=6,wtp=5,rec=10,attr=8,aware=7,edu=3,feas=4,build=7,ret=6,comp=2,expand=5,boring=8,excel=3,market=7,f10=5,f100=5)),

dict(id=34, name="Healthcare staffing agency credential files", ind="Staffing agencies",
 concept="Collect nurse/allied candidates' licenses, certs, health records, skills checklists; build client-ready submission packets.",
 customer="Healthcare staffing agencies 20–500 active clinicians", buyer="Credentialing coordinator / ops",
 problem="Every placement needs a complete compliance file; clients/Joint Commission audit them.", manual="ATS attachments + spreadsheets.",
 sucks="Expired docs block placements; constant chasing.", freq="Daily", consequence="Lost placements (revenue), audit findings.",
 swcat="Staffing credentialing", competitors="Bullhorn + add-ons, Ceipal, Credentially, ShiftWise/Aya tools, ATS modules",
 comp_pricing="Quote-based (approx., unverified)", gaps="Small agencies on general ATSs.", cat="B", domain="Medium", mvp="4 weeks",
 price="$199–$499", channel="Staffing associations, LinkedIn", niche="Per diem nurse staffing agencies", why_not="ATS ecosystems + agency churn; mid-market sales motion.",
 first_test="MAYBE", first_where="Google Maps 'nurse staffing agency', state staffing agency registrations (some states), LinkedIn.", payment="Short demo required",
 m1="Files built.", m6="Every placement.", y2="Sticky.", value="Prevents lost revenue, helps pass audits", must="Critical", tests="1,2,3,4,5,6,10 (7/12)",
 s=dict(pain=8,wtp=7,rec=9,attr=7,aware=8,edu=3,feas=6,build=5,ret=8,comp=4,expand=7,boring=9,excel=8,market=6,f10=6,f100=5)),

dict(id=35, name="Engineering/architecture firm license & CE tracking", ind="Professional services",
 concept="Track PE/RA licenses, firm certificates of authorization, CE hours across states.", customer="A/E firms 20–300 staff", buyer="Ops/HR",
 problem="Multi-state licenses for staff and firm.", manual="Spreadsheet.", sucks="Missed renewals block project stamping.",
 freq="Monthly across staff", consequence="Can't seal drawings; board discipline.", swcat="License tracking",
 competitors="Generic expiration trackers, HRIS, Deltek add-ons", comp_pricing="Varies", gaps="Few dedicated tools.",
 cat="B", domain="Low", mvp="2 weeks", price="$79–$199", channel="ACEC/AIA chapters", niche="Multi-state civil firms",
 why_not="Small market; low urgency except at renewal.", first_test="YES", first_where="State engineering board firm directories, ACEC member lists.", payment="Self-service",
 m1="Setup.", m6="Renewals.", y2="CE history.", value="Prevents compliance problems", must="Important", tests="1,3,4,6 (4/12)",
 s=dict(pain=6,wtp=5,rec=7,attr=6,aware=7,edu=3,feas=8,build=3,ret=7,comp=6,expand=4,boring=10,excel=9,market=3,f10=5,f100=4)),

dict(id=36, name="Independent auto dealer title & temp-tag tracker", ind="Automotive",
 concept="Track each sale's title receipt, payoff, temp tag expiry and DMV submission deadlines.",
 customer="Independent used-car dealers selling 20–200 cars/month", buyer="Title clerk / owner",
 problem="State deadlines to deliver titles/registrations; temp tags expire.", manual="Paper deal jackets + spreadsheets.",
 sucks="Lost titles, angry buyers, DMV complaints.", freq="Daily", consequence="Fines, dealer license complaints, chargebacks from lenders.",
 swcat="Dealer management systems (title module)", competitors="Frazer, DealerCenter, Wayne Reaves, AutoManager, state e-title systems",
 comp_pricing="DMS ~$100–$300/mo (approx.)", gaps="Title workflow weak in some DMSs.", cat="C", domain="Medium", mvp="3–4 weeks",
 price="$79–$199", channel="State dealer license lists", niche="Buy-here-pay-here dealers in one state", why_not="DMS overlap; dealers tolerate the pain; state-specific rules.",
 first_test="YES", first_where="State dealer license databases (public in many states), Google Maps 'used car dealer'.", payment="Short demo required",
 m1="Open deals tracked.", m6="Daily use.", y2="Habit.", value="Prevents fines, reduces customer complaints", must="Important", tests="1,2,3,4,9 (5/12)",
 s=dict(pain=7,wtp=6,rec=9,attr=9,aware=5,edu=5,feas=6,build=5,ret=7,comp=6,expand=5,boring=9,excel=7,market=6,f10=7,f100=6)),

dict(id=37, name="Small government contractor deliverables & reporting tracker", ind="Government contractors",
 concept="Track contract deliverables (CDRLs), reports, option dates, SAM renewal, small-business reporting.", customer="GovCons 10–200 staff", buyer="Contracts manager",
 problem="Many contract-specific deadlines.", manual="Spreadsheets.", sucks="Missed deliverables hurt CPARS.",
 freq="Weekly", consequence="Poor past performance ratings, payment holds.", swcat="GovCon contract management",
 competitors="Deltek, Unanet, GovDash, spreadsheets", comp_pricing="Mid-market ERP pricing", gaps="Lightweight tools.",
 cat="C", domain="Medium", mvp="3 weeks", price="$99–$299", channel="SAM.gov entity data, APEX accelerators", niche="Service contractors 10–50 staff",
 why_not="Customers see it as spreadsheet work; ERP vendors bundle.", first_test="YES", first_where="SAM.gov entity registrations & USAspending awards (public).", payment="Short demo required",
 m1="Contracts loaded.", m6="Deliverables.", y2="Contract lifecycles.", value="Prevents missed deadlines", must="Important", tests="1,2,4,7,11 (5/12)",
 s=dict(pain=6,wtp=6,rec=8,attr=7,aware=5,edu=6,feas=6,build=5,ret=7,comp=6,expand=6,boring=9,excel=9,market=5,f10=5,f100=4)),

dict(id=38, name="Multi-site facility compliance inspection calendar", ind="Facilities management",
 concept="Track recurring vendor inspections (fire, elevator, boiler, backflow, generator), collect reports, flag deficiencies per site.",
 customer="Multi-site orgs (private schools, churches, retail chains, small PM firms) with 5–100 sites", buyer="Facilities director",
 problem="Dozens of statutory inspections per site on different cycles.", manual="Spreadsheet + vendor emails with PDFs.",
 sucks="Missed inspections found by fire marshal/insurer.", freq="Weekly across sites", consequence="Fines, insurance issues, life-safety risk.",
 swcat="CMMS / compliance management", competitors="UpKeep, MaintainX, Limble, Brightly (Siemens), spreadsheets",
 comp_pricing="CMMS ~$20–$75/user/mo (approx.)", gaps="CMMS is work-order-centric, not compliance-evidence-centric.",
 cat="B", domain="Low", mvp="3 weeks", price="$99–$399", channel="Facility manager associations (IFMA), LinkedIn", niche="Private school networks / dioceses",
 why_not="Buyers are hard to list; CMMS vendors can add a compliance view.",
 first_test="MAYBE", first_where="LinkedIn 'facilities director', private school directories, IFMA chapters.", payment="Short demo required",
 m1="Inventory built.", m6="Inspections recur.", y2="Evidence archive.", value="Prevents fines, reduces liability", must="Critical", tests="1,2,3,4,5,9,10,11 (8/12)",
 s=dict(pain=7,wtp=6,rec=9,attr=5,aware=7,edu=3,feas=7,build=4,ret=8,comp=5,expand=7,boring=10,excel=9,market=6,f10=4,f100=5)),

dict(id=39, name="3PL monthly client billing from warehouse activity", ind="Warehouses / Logistics",
 concept="Import WMS/shipping activity, apply each client's rate card (storage, picks, VAS), produce invoices + audit detail.",
 customer="Small 3PLs with 10–100 clients", buyer="Owner / billing manager",
 problem="Monthly billing compiled by hand from multiple exports.", manual="Excel rate cards + WMS exports.",
 sucks="Days of work; unbilled activity; disputes.", freq="Monthly (some weekly)", consequence="Lost revenue (unbilled fees), disputes.",
 swcat="3PL billing", competitors="3PL WMS billing modules (Extensiv, Logiwa, Packiyo, Deposco), tariff managers, QuickBooks",
 comp_pricing="Included in WMS; standalone varies (approx.)", gaps="3PLs on WMSs with weak billing.",
 cat="B", domain="Medium", mvp="5–6 weeks", price="$199–$499", channel="3PL directories, Google Maps", niche="E-commerce fulfillment 3PLs on ShipStation-type stacks",
 why_not="WMS integration variety; WMS vendors' billing modules.", first_test="YES", first_where="Google Maps '3PL fulfillment', 3PL directories (e.g., fulfillment marketplaces), LinkedIn.", payment="Short demo required",
 m1="First invoice run.", m6="Monthly.", y2="Rate-card logic accumulates.", value="Prevents lost revenue, saves time", must="Important", tests="1,2,4,7,8,9 (6/12)",
 s=dict(pain=8,wtp=7,rec=10,attr=7,aware=7,edu=3,feas=5,build=6,ret=8,comp=5,expand=7,boring=9,excel=10,market=6,f10=6,f100=5)),

dict(id=40, name="Veterinary controlled-substance log & DEA inventory", ind="Healthcare administration (veterinary)",
 concept="Digital controlled-drug logs, running balances, discrepancy flags, biennial inventory, audit export.",
 customer="Independent vet clinics (1–5 locations)", buyer="Practice manager / DEA registrant vet",
 problem="Every dose logged; balances reconciled; biennial inventory.", manual="Paper logbooks.",
 sucks="Math errors, illegible entries, audit anxiety.", freq="Daily", consequence="DEA fines, registration risk, diversion.",
 swcat="Controlled-substance log software", competitors="VetSnap, Vet S8, PIMS modules, dispensing cabinets (e.g., Cubex)",
 comp_pricing="Varies (via search Oct 2026)", gaps="Paper still common in independents.", cat="C", domain="Medium", mvp="3–4 weeks",
 price="$79–$199", channel="Google Maps vet clinics + vet practice-manager groups (VHMA)", niche="Independent small-animal clinics",
 why_not="Must meet DEA recordkeeping rules exactly; specialized competitors exist; clinics tolerate paper.",
 first_test="YES", first_where="Google Maps 'veterinary clinic' (~30k US clinics), state veterinary board lists.", payment="Short demo required",
 m1="Logs digitized.", m6="Daily use.", y2="Records retention.", value="Prevents fines, helps pass audits", must="Critical", tests="1,2,3,9,10 (5/12)",
 s=dict(pain=7,wtp=6,rec=10,attr=9,aware=6,edu=4,feas=7,build=4,ret=8,comp=5,expand=5,boring=10,excel=3,market=6,f10=7,f100=6)),
]
